### ISSUE TITLE
Is there a way to specify the IP or network interface?

### ISSUE THREAD

**Issue by bronsen** [mateoradman/swift_file#3]
sf seems to bind to the first device it finds. In my case these are not accessible from outside the computer, so my mobile cannot connect.

Can I specify which IP address or what network device (lo, wlo1, enx806d973060ab, etc...) sf will use?

**Comment by mateoradman** [comment]
Hi @bronsen, thanks for your question.
Right now, sf will automatically bind to `0.0.0.0`. It is not possible to provide a custom IP address or a network device but I am going to include this feature in the next release.
