### ISSUE TITLE
--no-open still opens the received file

### ISSUE THREAD

**Issue by d0tcc** [mateoradman/swift_file#6]
Hi, I'm having issues with the --no-open flag as it still opens the file after the file was received.

This is my command and the output:

```
> sf receive --no-open
URL: http://192.168.169.68:1024/receive
<QR CODE>
Server launched on 0.0.0.0:1024
File `file.jpg` with content type `image/jpeg`, size 72823 bytes has been transferred to /path/to/file.jpg
File opened using a default program.
```

I'm using version 0.1.5 of swift_file on Ubuntu 22.04.2 LTS x86_64

Thanks for the awesome project!

**Comment by mateoradman** [comment]
Thanks for reporting the bug, @d0tcc! I will include the fix in the next release 🙂
